#!/bin/sh
#
# (c) ben, untar.org
#

BIN='apti'
TITEL='install a apt package'
DESC='An alias for: sudo apt-get install'
ARGS='<pattern>'

set -e
set -u

usage() {
    echo "Usage: $BIN $ARGS";
    exit 1;
}
[ $# = 1 ] || usage

case "$1" in
	-h|--help)
        echo "Title: $BIN - $TITEL"
        echo "Description: $DESC"
        usage ;;
	-*|--*) usage;;
     *) break;;
esac

pat="$1"
sudo apt-get install "$pat"
