#!/bin/sh
#
# (c) ben, untar.org
#

BIN='aptl'
TITEL='Show installed packages'
DESC='Filters: dpkg --get-selections'
ARGS='[-h|--help] <pattern>'

set -e
set -u

usage() { echo "Usage: $BIN $ARGS"; exit 1; }

[ $# = 1 ] || usage

case "$1" in
	-h|--help)
        echo "Title: $BIN - $TITEL"
        echo "Description: $DESC"
        usage ;;
	-*|--*) usage;;
     *) break;;
esac

pat="$1"

dpkg --get-selections | awk '{ print $1 }' | grep "$pat"
