#!/bin/sh
#
# (c) ben, untar.org
#

PROG='aptr'
TITEL='remove a package with apt'
DESC='an alias for: sudo apt-get remove --purge <pattern>'
ARGS='[-h|--help] <pattern>'

set -e
set -u

usage() { echo "Usage: $PROG $ARGS"; exit 1; }

[ $# = 1 ] || usage

case "$1" in
	-h|--help)
        echo "Title: $PROG - $TITEL"
        echo "Description: $DESC"
        usage ;;
	-*|--*) usage;;
     *) break;;
esac

pat="$1"

sudo apt-get remove --purge "$pat"
