#!/bin/sh
#
# (c) ben, untar.org
#

PROG='ctar'
TITEL='create a tar.gz file'
DESC='just an alias for "tar cfvz item.tar.gz item"'
ARGS='[-h|--help] <file|dir>'

set -e
set -u

usage() { echo "Usage: $PROG $ARGS"; exit 1; }

[ $# = 1 ] || usage

case "$1" in
	-h|--help)
        echo "Title: $PROG - $TITEL"
        echo "Description: $DESC"
        usage ;;
	-*|--*) usage;;
     *) break;;
esac

src="$1"
target="${src}".tar.gz

tar cfvz $target $src

