#!/bin/sh
#
# (c) ben, untar.org
#

PROG=findi
TITEL='a find shortcut'
DESC='A find shortcut that runs: find . -iname <pattern>'
ARGS='<pattern>'

set -e
set -u

usage() { echo "Usage: $PROG $ARGS"; exit 1; }

[ $# = 1 ] || usage 

case "$1" in
    -h|--help)
        echo "Title: $PROG - $TITEL"
        echo "Description: $DESC"
        usage ;;
    -*|--*) usage;;
     *) break;;
esac

find . -iname "$1"
