#!/bin/sh
#
# (c) ben, untar.org
#

PROG='runbang'
TITEL='extract and execute the shebang interpreter'
DESC='Takes the shebang interpreter and runs the script with it, usefull for vim.'
ARGS='[-h|--help] <file>'

set -e
set -u

usage() { echo "Usage: $PROG $ARGS"; exit 1; }

[ $# = 1 ] || usage

case "$1" in
	-h|--help)
        echo "Title: $PROG - $TITEL"
        echo "Description: $DESC"
        usage ;;
	-*|--*) usage;;
     *) break;;
esac

# find shebangs, args are allowed:  '#!/usr/bin/perl -w'
intp=$(head -n 1 "$1" | perl -wpl -e 's/.*\/(\w+\s*.*)\s*$/$1/g')

${intp} "$1"
