#!/bin/sh
#
# (c) ben, untar.org
#

PROG=xclone
TITEL='git clone from xclip'
DESC='Runs the "git clone <url>" with an url taken from xclip -o.'
ARGS=''

set -e
set -u

usage() { echo "Usage: $PROG $ARGS"; exit 1; }

if [ $# = 0 ] ; then
    git clone `xclip -o`
else
    case "$1" in
        -h|--help)
            echo "Title: $PROG - $TITEL"
            echo "Description: $DESC"
            usage ;;
        -*|--*) usage;;
         *) break;;
    esac
fi

