#!/bin/sh

#     (c) 2011 Ben, untar.org
#
PROG=xget
TITEL='Wget from xclip'
USAGE='<url>'

usage(){
    echo "Usage: $PROG - $USAGE"
    exit 1
}

if [ "$#" = 0 ] ;then usage; fi
pat="$1"

wget `xclip -o`
