#!/bin/sh
#
# (c) ben, untar.org
#

PROG=xget
TITEL='Wget from xclip'
DESC='Runs the wget utility with an url taken from xclip -o.'
ARGS='<url>'

set -e
set -u

usage() { echo "Usage: $PROG $ARGS"; exit 1; }

if [ $# = 0 ] ; then
    wget `xclip -o`
else
    case "$1" in
        -h|--help)
            echo "Title: $PROG - $TITEL"
            echo "Description: $DESC"
            usage ;;
        -*|--*) usage;;
         *) break;;
    esac
fi

